# Generated by Django 5.1 on 2024-10-17 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('costo', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='productos')),
                ('categoria', models.TextField()),
                ('dias', models.IntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(7)])),
            ],
        ),
    ]
