# Generated by Django 5.1.2 on 2024-11-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_renta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='veces_rentado_mes',
            field=models.IntegerField(default=0),
        ),
    ]
