# Generated by Django 5.1 on 2024-11-15 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_renta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renta',
            old_name='id_libro',
            new_name='id_producto',
        ),
    ]
