# Generated by Django 5.1 on 2024-11-15 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_rename_id_libro_renta_id_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renta',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentas', to='producto.producto', verbose_name='Titulo'),
        ),
    ]
