# Generated by Django 5.1 on 2024-11-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_alter_renta_id_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='renta',
            name='fecha_devuelto',
            field=models.DateField(null=True),
        ),
    ]
