# Generated by Django 5.1 on 2024-10-16 17:22

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellidopaterno', models.CharField(max_length=40)),
                ('apellidomaterno', models.CharField(max_length=40)),
                ('puntos', models.IntegerField(default=100)),
                ('celular', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('nocuenta', models.CharField(max_length=9)),
                ('area', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
