# Generated by Django 5.1.2 on 2024-11-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_oculto_alter_usuario_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='devoluciones_tardias',
            field=models.IntegerField(default=0),
        ),
    ]
